// User-supplied production boot ROMs. Vite inlines this module into the
// self-contained HTML artifact, so the emulator never performs a BIOS fetch.
const BIOS_BASE64 = {
  dmg: [
    "Mf7/ryH/nzLLfCD7ISb/DhE+gDLiDD7z4jI+d3c+/OBHEQQBIRCAGs2VAM2WABN7/jQg8xHYAAYIGhMiIwUg+T4Z6hCZ",
    "IS+ZDgw9KAgyDSD5Lg8Y82c+ZFfgQj6R4EAEHgIODPBE/pAg+g0g9x0g8g4TJHweg/5iKAYewf5kIAZ74gw+h+LwQpDgQ",
    "hUg0gUgTxYgGMtPBgTFyxEXwcsRFwUg9SIjIiPJzu1mZswNAAsDcwCDAAwADQAIER+IiQAO3Mxu5t3d2Zm7u2djbg7szN",
    "3cmZ+7uTM+PEK5pbmlQjwhBAERqAAaE74g/iN9/jQg9QYZeIYjBSD7hiD+PgHgUA==",
  ].join(""),
  cgb: [
    "Mf7/PgLDfADTAJigEtMAgABAHlPQAB9CHAAUKk0ZjH4AfDFuSkVSSgAA/1MffP8DHwD/H6cA7xsfAO8bAHwAAP8Dzu1mZswN",
    "AAsDcwCDAAwADQAIER+IiQAO3Mxu5t3d2Zm7u2djbg7szN3cmZ+7uTM+PEK5pbmlQjxYQ+BwPvzgR811As0AAibQzQMCIQD+",
    "DqCvIg0g/BEEASEQgEwa4gzNxgPNxwMTe/40IPERcgAGCBoTIiMFIPnN8AM+AeBPPpHgQCGymAZODkTNkQKv4E8OgCFCAAYY",
    "8gy+IP4jBSD3ITQBBhl4hiwFIPuGIP7NHAMYAgAAzdAFr+BwPhHgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAhAICvIstsKPvJKhITDSD6yeUhD//LhstGKPzhyREA/yED0A4PPjASPiASGi+hyzdHPhASGi+hsE9+qebwRyqp",
    "obAyR3l3PjASyT6A4Gjgag5rKuIFIPtKCUMOaSriBSD7ycXV5SEA2AYBFj8eQM1KAuHRwck+gOAm4BE+8+AS4CU+d+AkITD/",
    "rw4QIi8NIPvJzRECzWICef44IBTlr+BPIaeZPjgiPP4/IPo+AeBP4cXlIUMBy37MiQXhwc0RAnnWMNIGA3n+AcoGA33+0Sgh",
    "xQYDDgEWA37m+LEiFSD4DHn+BiDwEREAGQUg5xGh/xnBBHgeg/5iKAYewf5kIAd74BM+h+AU+gLQ/gAoCj3qAtB5/gHKkQIN",
    "wpECyQ4mzUoDzRECzWICDSD0zRECPgHgT80+A81BA6/gT80+A8khCAARUf8OBc0KAsnF1eUhQNgOIH7mH/4fKAE8VyoHBwfm",
    "B0c6BwcH5hiw/h8oATwPDw9H5uCyInjmA19+Dw/mH/4fKAE8BwezIg0gx+HRwckOABrm8MtJKALLN0cjfrAiGuYPy0kgAss3",
    "RyN+sCITy0EoDdUR+P/LSSgDEQgAGdEMef4YIMzJR9UWBFjLEBfLExcVIPbRIiMiI8k+GeoQmSEvmQ4MPSgIMg0g+S4PGPPJ",
    "PgHgT80AAhEHBiGAgA7AGiIjIiMTDSD3EQQBzY8DAaj/Cc2PAwH4/wkRcgAOCCMaIhMNIPkhwpgGCD4IDhAiDSD8ERAAGQUg",
    "86/gTyHCmD4IIjz+GCACLuL+KCADIQKZ/jgg7SHYCBFA2AYIPv8SExITDgLNCgI+ABITEhMTEwUg6s1iAiFLAX7+MyALLkQe",
    "MCq7IEkcGAQuSx4BKrsgPi40ARAAKoBHDSD66gDQIccGDgAquCgIDHn+TyD2GB951kE4HCEWBxYAXxn6NwFXfrooDREOABl5",
    "g0/WXjjtDgAhMwcGAAl+5h/qCNB+5uAHBwfqC9DN6QTJEZEHIQDZ+gvQRw4ey0AgAhMTGiIgAhsby0ggAhMTGiITEyACGxvL",
    "UCgFGysaIhMaIhMNINchANkRANrNZAXJIRIA+gXQBwcGAE8JEUDYBgjlDgLNCgITExMTExPhBSDwEULYDgLNCgIRStgOAs0K",
    "AisrEUTYDgLNCgLJDmAq5cUh6AcGAE8JDgjNCgLB4Q0g7Mn6CNARGAA8PSgDGSD6yc0dAnjm/ygPIeQIBgAquSgIBHj+DCD2",
    "GC146gXQPh7qAtARCwAZVnrmH18hCNA6Int3eubgBwcHXyEL0Doie3fN6QTNKAXJzREC+kMBy38oBOBMGCg+BOBMPgHgbCEA",
    "2s17BQYQFgAeCM1KAiF6APoA0EcOAiq4zNoDDSD4yQEPP37//8AAwPDxA3z8/v4DBwcP4ODw8B4+fv4PDx8f//8AAAEBAQP/",
    "/+HgwPD5+x9/+ODz/T4e4PD5fz58+OD48PD4AAB/fwcPn7+eH///Dx4+PPH7f3/+3t+fHz8+PPj4AAADAwcH///BwPPn9/PA",
    "wMDAHx8ePj8fPj6AAAAAfB8HAA///gB8+PAAHw8PAHz4+AA/PhwADw8PAHz//wAA+PgABw8PAIH//wDz4YAA4P9/APzwwAA+",
    "fHwAAAAAAACIFjbR2/I8jJI9XFjJPnAdWWkZNagUqnWVmTRvFf+XS5AXEDn39qJJTkNo4Ivwzgwp6LeGmlIBnXGcvV1tZz9r",
    "s0YopcbTJ2EYZmq/DfRCRUZBQVJCRUtFSyBSLVVSQVIgSU5BSUxJQ0UgUnwIEqOiB4dLIBJlqBaphrFooIdmEqEwPBKFEmQb",
    "BwZvbm6ur2+yr7Koq2+vhq6iohKvExKhbq+vrQZMbq+vEnysqGpuE6AtqCusZKxth7xgtBNyfLWurnx8ZaJsZIWAsECIIGje",
    "AHDeIHggIDggsJAgsKDgsMCYtkiA4FAeHlgguOCIsBAgABAg4BjgGAAY4CCo4CAY4AAgGNjIGOAA4EAoKCgY4GAgGOAAAAjg",
    "GDDQ0NAg4Oj/f78y0AAAAJ9jeUKwFcsE/38xbkpFAAD/f+8bAAIAAP9/H0LyHAAA/3+UUkopAAD/f/8DLwEAAP9/7wPWAQAA",
    "/3+1Qsg9AAB0fv8DgAEAAP9nrHcTGmst1n7/S3UhAAD/U19KUn4AAP9P0n5MOuAc7QP/f18lAABqAx8C/wP/f/9/3wESAQAA",
    "HyNfA/IACQD/f+oDHwEAAJ8pGgAMAAAA/39/Ah8AAAD/f+ADBgIgAf9/634fAAB8/3//PwB+HwD/f/8DHwAAAP8DHwAMAAAA",
    "/38/A5MBAAAAAABCfwP/f/9/jH4AfAAA/3/vG4BhAAD/fwB84AMffB8A/wNAQUIgISKAgYIQERISsHm4rRYXB7oFfBMAAAAA",
  ].join(""),
};

function decodeBase64(value) {
  const binary = atob(value);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

const BIOS_BYTES = {
  dmg: decodeBase64(BIOS_BASE64.dmg),
  cgb: decodeBase64(BIOS_BASE64.cgb),
};

export const EMBEDDED_BIOS_INFO = Object.freeze({
  dmg: Object.freeze({ size: BIOS_BYTES.dmg.length, revision: "Production DMG" }),
  cgb: Object.freeze({ size: BIOS_BYTES.cgb.length, revision: "Production GBC" }),
});

export function getEmbeddedBootROM(model) {
  const bios = BIOS_BYTES[model];
  if (!bios) throw new Error(`No embedded BIOS is available for ${model}.`);
  return bios.slice();
}
