import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

const htmlUrl = new URL("../public/gbc-lab.html", import.meta.url);
const romRootUrl = new URL("../SELECT_ROMS/", import.meta.url);

test("builds the complete emulator as the only self-contained public file", async () => {
  assert.deepEqual(await readdir(new URL("../public/", import.meta.url)), ["gbc-lab.html"]);
  const html = await readFile(htmlUrl, "utf8");
  const romFiles = (await readdir(romRootUrl))
    .filter((fileName) => /\.(gb|gbc)$/i.test(fileName))
    .sort((left, right) => left.localeCompare(right));
  assert.equal(romFiles.length, 40);
  for (const fileName of romFiles) {
    const romBase64 = Buffer.from(
      await readFile(new URL(encodeURIComponent(fileName), romRootUrl)),
    ).toString("base64");
    const artworkName = fileName.replace(/\.(gb|gbc)$/i, ".png");
    const artworkBase64 = Buffer.from(
      await readFile(new URL(`artwork/${encodeURIComponent(artworkName)}`, romRootUrl)),
    ).toString("base64");
    assert.ok(html.includes(romBase64), `${fileName} was not embedded`);
    assert.ok(html.includes(artworkBase64), `${artworkName} was not embedded`);
  }
  assert.match(html, /<title>GAMEBOY LAB — Browser Game Boy Emulator<\/title>/i);
  assert.match(html, /GAMEBOY LAB/);
  assert.match(html, /PLAY · SAVE · PRESERVE/);
  assert.doesNotMatch(html, /HARDWARE RESPONSE CORE/);
  assert.match(html, /ADD ROM/);
  assert.match(html, /LCD response/i);
  assert.match(html, /Ghosting strength/i);
  assert.match(html, /Game Boy contrast/i);
  assert.match(html, /Screen only/i);
  assert.match(html, /DMG cartridge palette/i);
  assert.match(html, /Pastel Mix/i);
  assert.match(html, /Keyboard button motion/i);
  assert.match(html, /Audio volume/i);
  assert.doesNotMatch(html, /Save center/i);
  assert.match(html, /SAVE OPTIONS/i);
  assert.match(html, /HOVER FOR SAVE OPTIONS/i);
  assert.match(html, /DOWNLOAD \.SAV/i);
  assert.match(html, /Save states/i);
  assert.match(html, /save-state-carousel/);
  assert.match(html, /save-state-preview-placeholder/);
  assert.match(html, /DOWNLOAD ALL SAVES/i);
  assert.match(html, /RESTORE BACKUP/i);
  assert.match(html, /REPLACE & RESTORE/i);
  assert.match(html, /Manual Game Boy scale/i);
  assert.match(html, /Audio buffering/i);
  assert.match(html, /Why the GBC colours look different/i);
  assert.match(html, /How pixel scaling works/i);
  assert.match(html, /How much sound stays ready/i);
  assert.match(html, /What frame skipping actually skips/i);
  assert.match(html, /Host catch-up budget/i);
  assert.match(html, /Cartridge insertion animation/i);
  assert.match(html, /Game library/i);
  assert.match(html, /FIND YOUR GAMES HERE/i);
  assert.match(html, /BUILT IN/i);
  assert.match(html, /LOCAL CARTRIDGE ARCHIVE/i);
  assert.match(html, /ADD ROM/i);
  assert.match(html, /ARTWORK: LIBRETRO WHEN AVAILABLE/i);
  assert.match(html, /The Legend of Zelda: Link's Awakening DX/);
  assert.match(html, /Pokémon Crystal Version/);
  assert.match(html, /Pokémon Pinball/);
  assert.match(html, /Pokémon Trading Card Game/);
  assert.match(html, /Super Mario Land 2: 6 Golden Coins/);
  assert.doesNotMatch(html, />Blend</i);
  assert.match(html, /data:image\/svg\+xml/);
  assert.match(html, /viewBox=["']10 4 44 57["']/);
  assert.doesNotMatch(
    await readFile(new URL("../app/Emulator.jsx", import.meta.url), "utf8"),
    /<rect width="64" height="64" fill="#17191e"/,
  );
  assert.doesNotMatch(html, /rx=['"]14['"]/);
  assert.doesNotMatch(html, /<script[^>]+\bsrc=/i);
  assert.doesNotMatch(html, /<link[^>]+\brel=["']stylesheet["']/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|react-loading-skeleton/i);
});

test("keeps the project local and free of deployment dependencies", async () => {
  const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const viteConfig = await readFile(new URL("../vite.config.ts", import.meta.url), "utf8");
  const installed = { ...packageJson.dependencies, ...packageJson.devDependencies };
  for (const dependency of [
    "@cloudflare/vite-plugin",
    "drizzle-orm",
    "drizzle-kit",
    "next",
    "vinext",
    "wrangler",
  ]) {
    assert.equal(installed[dependency], undefined);
  }
  assert.equal(packageJson.scripts.deploy, undefined);
  assert.equal(packageJson.scripts.start, undefined);
  assert.equal(packageJson.scripts["sync:artwork"], "node scripts/sync-libretro-artwork.mjs");
  assert.match(viteConfig, /gameboy-lab-private-library/);
  assert.match(viteConfig, /\.\/SELECT_ROMS\//);
  assert.match(viteConfig, /readdirSync\(embeddedRomRoot\)/);
  assert.match(viteConfig, /EMBEDDED_LIBRARY_ROMS/);
  assert.match(viteConfig, /embeddedDisplayTitle/);
  assert.match(viteConfig, /replace\(\/\^Pokemon\\b\/, "Pokémon"\)/);
  assert.match(viteConfig, /cartridgeKind: cgb \? "gbc" : "gb"/);
  assert.doesNotMatch(viteConfig, /embeddedRomPath|Super Mario Land/);
});

test("keeps every hardware input and new option accessible", async () => {
  const html = await readFile(htmlUrl, "utf8");
  const source = await readFile(new URL("../app/Emulator.jsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const shader = await readFile(new URL("../app/lib/lcdShader.js", import.meta.url), "utf8");
  const optionsStart = source.indexOf('id="options-drawer"');
  const optionsEnd = source.indexOf("</aside>", optionsStart);
  const emulationStart = source.indexOf('id="emulation-drawer"');
  const emulationEnd = source.indexOf("</aside>", emulationStart);
  const saveDrawerStart = source.indexOf('id="save-drawer"');
  assert.ok(optionsStart >= 0 && optionsEnd > optionsStart);
  assert.ok(emulationStart > optionsEnd && emulationEnd > emulationStart);
  assert.ok(saveDrawerStart > optionsEnd);
  assert.doesNotMatch(source.slice(optionsStart, optionsEnd), /<SaveCenter|Save center/);
  assert.doesNotMatch(source.slice(optionsStart, optionsEnd), /LOAD ROM|fileRef\.current\?\.click/);
  assert.match(source.slice(optionsStart, optionsEnd), /DOWNLOAD ALL SAVES/);
  assert.match(source.slice(optionsStart, optionsEnd), /RESTORE BACKUP/);
  assert.doesNotMatch(source.slice(optionsStart, optionsEnd), /Audio buffering|Frame skipping/);
  assert.match(source.slice(emulationStart, emulationEnd), /Audio buffering/);
  assert.match(source.slice(emulationStart, emulationEnd), /Frame skipping/);
  assert.doesNotMatch(source.slice(emulationStart, emulationEnd), /DOWNLOAD ALL SAVES|RESTORE BACKUP/);
  assert.doesNotMatch(source, /className="transport"/);
  for (const label of ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]) {
    assert.match(html, new RegExp(`(?:sub)?label.{0,5}${label}`, "i"));
  }
  assert.match(html, /Ghosting strength/i);
  assert.match(html, /native-persistence,dmg-analytic-dot-matrix,cgb-analytic-rgb-stripe/);
  assert.match(source, /window\.devicePixelRatio/);
  assert.match(source, /Math\.floor\(contentLimit \* density \/ GAMEBOY_WIDTH\)/);
  assert.match(source, /pixelScale \* GAMEBOY_WIDTH \/ \(screenContentWidth \* density\)/);
  assert.match(source, /outerWidth = baseContentWidth \* LCD_FRAME_RATIO/);
  assert.match(source, /pixelScale: integerScale/);
  assert.match(source, /const nextScale = fit \* manualScale \/ 100[\s\S]*setConsoleScale\(nextScale\)/);
  assert.match(source, /const insertedTipHeight = cartridgePresent \? 20 : 0/);
  assert.doesNotMatch(source, /cartridgeAllowance|interactiveHeight|snappedPhysicalWidth/);
  assert.match(source, /preserveAspectRatio="xMidYMid meet"/);
  assert.match(source, /rigTopWithoutOffset = wrapRect\.top \+ \(wrapRect\.height - rigRect\.height\) \/ 2/);
  assert.match(source, /const baselineCenterOffset = cartridgePresent/);
  assert.match(source, /const hoverDuck = baselineCenterOffset/);
  assert.match(source, /useLayoutEffect\(\(\) => \{\s*let frame = 0;\s*const measureEnvelope/s);
  assert.match(source, /const clearanceActive = \([\s\S]*cartridgeHovered[\s\S]*cartridgePreflight[\s\S]*showSaveTooltip/s);
  assert.match(source, /const nextOffset = clearanceActive[\s\S]*Math\.max\(hoverDuck, Math\.max\(0, collisionSafeOffset\)\)[\s\S]*baselineCenterOffset/s);
  assert.match(source, /consoleOffsetYRef\.current = nextOffset[\s\S]*setConsoleOffsetY\(nextOffset\)/);
  assert.match(source, /className="cartridge-collision-anchor"/);
  assert.match(css, /\.has-cartridge \.cartridge-collision-anchor\s*\{[^}]*top:\s*-20px/s);
  assert.doesNotMatch(css, /\.cartridge-inserting \.cartridge-collision-anchor/);
  assert.match(source, /const contentWidth = contentLimit/);
  assert.match(source, /function drawBlankScreen\(context, model\)[\s\S]*model === "cgb" \? \[232, 232, 224\] : \[202, 220, 159\]/);
  assert.match(source, /const preservePause = pausedRef\.current[\s\S]*if \(preservePause\)[\s\S]*drawBlankScreen\(context, nextModel\)[\s\S]*lcdRendererRef\.current\?\.uploadFrame\([\s\S]*resetHistory:\s*true[\s\S]*releaseDisplayTransition\(\)/);
  assert.match(source, /const completeViewModeTransition = useCallback\([\s\S]*setViewModeTransition\(""\)[\s\S]*replayCartridgeInsertion\(\{ waitForGeometry: false \}\)/);
  assert.match(source, /const viewTransitionPendingRef = useRef\(null\)/);
  assert.match(source, /sourceBounds:\s*\{[\s\S]*left:\s*sourceBounds\.left[\s\S]*width:\s*sourceBounds\.width/s);
  assert.match(source, /targetScreenWidthRef\.current = outerWidth[\s\S]*setScreenGeometry/);
  assert.match(source, /targetAncestorScaleX = targetBounds\.width \/ Math\.max\(1, frame\.offsetWidth\)[\s\S]*localDeltaX = deltaX \/ Math\.max\(0\.001, targetAncestorScaleX\)/s);
  assert.match(source, /const inverseTransform = \([\s\S]*translate3d\(\$\{localDeltaX\}px, \$\{localDeltaY\}px, 0\)[\s\S]*scale\(\$\{scaleX\}, \$\{scaleY\}\)/);
  assert.match(source, /const animation = frame\.animate\([\s\S]*transform:\s*inverseTransform[\s\S]*transform:\s*"translate3d\(0, 0, 0\) scale\(1, 1\)"/s);
  assert.doesNotMatch(source, /bezelAnimation|SCREEN_FRAME_ANIMATED_STYLES/);
  assert.match(source, /shellClone\.querySelector\("\.screen-frame"\)\?\.remove\(\)[\s\S]*console-transition-shell[\s\S]*document\.body\.append\(shellGhost\)/s);
  assert.match(source, /sourceHandheld\.style\.visibility = "hidden"[\s\S]*sourceFrame\.style\.visibility = "visible"/s);
  assert.match(source, /shellAnimation = shellGhost\.animate\([\s\S]*opacity:\s*1[\s\S]*opacity:\s*0[\s\S]*:\s*240/s);
  assert.doesNotMatch(source, /shellBezelAnimation|displayBezel\.animate|targetBezelStyle/);
  assert.match(source, /Promise\.all\(transitionFinishes\)[\s\S]*completeViewModeTransition\(pending\.run\)/s);
  assert.match(source, /frame\.style\.transform = "translate3d\(0, 0, 0\) scale\(1, 1\)"[\s\S]*setViewModeTransition\(""\)[\s\S]*requestAnimationFrame/s);
  assert.match(source, /lcdRendererRef\.current\?\.resizeAndRender\(duration \+ 120\)/);
  assert.match(source, /sourcePauseWidth[\s\S]*pauseCorrection[\s\S]*pauseOverlay\.animate/s);
  assert.doesNotMatch(source, /lcd-view-transition-overlay|syncLiveLcd|pauseIndicator\.cloneNode/);
  assert.doesNotMatch(source, /document\.startViewTransition|flushSync/);
  assert.doesNotMatch(css, /\.lcd-view-transition-overlay/);
  assert.match(css, /\.screen-frame\s*\{[^}]*border:\s*calc\(var\(--lcd-bezel-width,\s*8px\) \* 2 \/ 3\) solid #292c32[^}]*border-radius:\s*calc\(var\(--lcd-bezel-width,\s*8px\) \* \.4\)[^}]*background:\s*#121719/s);
  assert.doesNotMatch(css, /\.screen-frame\s*\{[^}]*outline:/s);
  assert.match(source, /className="screen-inner"/);
  assert.match(css, /\.dmg \.screen-inner\s*\{[^}]*border:\s*calc\(var\(--lcd-bezel-width,\s*8px\) \/ 3\) solid #121719[^}]*background:\s*#121719/s);
  assert.match(css, /\.display-bezel\s*\{[^}]*display:\s*flex[^}]*align-items:\s*center[^}]*justify-content:\s*center/s);
  assert.doesNotMatch(css, /\.dmg \.screen-frame\s*\{[^}]*translate:/s);
  assert.match(css, /\.screen-frame::after\s*\{[^}]*content:\s*none/s);
  assert.match(css, /\.cgb \.screen-frame\s*\{[^}]*border-color:\s*#0d0f13[^}]*box-shadow:\s*none/s);
  assert.doesNotMatch(css, /\.cgb \.screen-frame::after/);
  assert.match(css, /\.screen-frame\s*\{[^}]*margin:\s*0[^}]*transform:\s*none/s);
  assert.match(css, /\.console-wrap\.view-zoom-in \.screen-frame,[\s\S]*\.console-wrap\.view-zoom-out \.screen-frame\s*\{[^}]*transition:\s*none/s);
  assert.doesNotMatch(css, /\.console-wrap\.view-zoom-in \.screen-frame,[^}]*visibility:\s*hidden/s);
  assert.match(css, /\.console-wrap\.view-zoom-in \.handheld,[\s\S]*\.console-wrap\.view-zoom-in \.display-bezel\s*\{[^}]*visibility:\s*hidden/s);
  assert.match(css, /\.console-wrap\.view-zoom-in \.screen-frame\s*\{[^}]*visibility:\s*visible/s);
  assert.match(css, /\.console-wrap\.view-zoom-in \.display-bezel,[\s\S]*\.console-wrap\.view-zoom-out \.display-bezel\s*\{[^}]*z-index:\s*30[^}]*isolation:\s*isolate/s);
  assert.match(css, /\.console-transition-shell\s*\{[^}]*position:\s*fixed[^}]*z-index:\s*10[^}]*will-change:\s*opacity/s);
  assert.match(css, /\.console-wrap\.view-zoom-in,[\s\S]*\.console-wrap\.view-zoom-out\s*\{[^}]*z-index:\s*20[^}]*isolation:\s*isolate/s);
  assert.match(css, /\.console-wrap\.view-zoom-in \.device-rig,[\s\S]*\.console-wrap\.view-zoom-out \.device-rig\s*\{[^}]*z-index:\s*20[^}]*transition:\s*none/s);
  assert.doesNotMatch(css, /::view-transition|@keyframes view-mode-zoom/);
  assert.match(css, /\.console-wrap\.view-zoom-in \.cartridge-visual-rig,[\s\S]*\.console-wrap\.view-zoom-out \.cartridge-hover-rig\s*\{[^}]*visibility:\s*hidden/s);
  assert.match(source, /prefers-reduced-motion: reduce[\s\S]*\? 1[\s\S]*: 420/);
  assert.match(source, /const cartridgeBusy = cartridgeSwitching \|\| cartridgeStarting/);
  assert.match(source, /const presentationAnimationLocked = Boolean\([\s\S]*viewModeTransition[\s\S]*cartridgeSwitching[\s\S]*cartridgePreflight[\s\S]*cartridgeInserting && cartridgeAnimationEnabled[\s\S]*showSaveTooltip[\s\S]*saveTooltipFading/s);
  assert.match(source, /const pauseForDrawer = useCallback\(\(\) => \{[\s\S]*cartridgeSwitchingRef\.current \|\| cartridgeStartingRef\.current[\s\S]*pauseOnStartupRef\.current = true/s);
  assert.match(source, /const releaseDrawerPause = useCallback\(\(\) => \{[\s\S]*pauseOnStartupRef\.current = false/s);
  assert.match(source, /const finishCartridgeStartup = useCallback\(\(\) => \{[\s\S]*setCartridgeStarting\(false\)[\s\S]*pauseGame\("menu"\)/s);
  assert.match(source, /const openOptions = useCallback\(\(\) => \{\s*pauseForDrawer\(\)/);
  assert.match(source, /const openLibraryDrawer = useCallback\(\(\) => \{[\s\S]*pauseForDrawer\(\)/);
  assert.match(source, /if \(!runningRef\.current \|\| pausedRef\.current\)[\s\S]*if \(bootRef\.current\.active\)/s);
  assert.match(source, /if \(frames\) \{[\s\S]*if \(cartridgeStartingRef\.current\)[\s\S]*finishCartridgeStartup\(\)/s);
  assert.match(source, /const pauseAfterStartupFrame = \([\s\S]*cartridgeStartingRef\.current[\s\S]*pauseOnStartupRef\.current[\s\S]*presentFrameRef\.current\?\.\(\{ resetHistory: true \}\)[\s\S]*emulator\.drainAudio\(\)/s);
  assert.doesNotMatch(source, /const reset = useCallback/);
  assert.match(css, /\.dmg \.cartridge-power-cover\s*\{[^}]*rgb\(202,\s*220,\s*159\)/s);
  assert.match(css, /\.cgb \.cartridge-power-cover\s*\{[^}]*rgb\(232,\s*232,\s*224\)/s);
  assert.match(source, /const scaleAnimationLocked = presentationAnimationLocked/);
  assert.match(source, /if \(scaleAnimationLocked\)[\s\S]*CAN’T CHANGE SCALE DURING ANIMATION/s);
  assert.match(source, /switchViewMode = useCallback[\s\S]*presentationAnimationLocked\) return/s);
  assert.match(source, /switchModel = useCallback[\s\S]*presentationAnimationLocked\) return/s);
  assert.match(source, /aria-pressed=\{viewMode === "screen"\}[\s\S]*disabled=\{presentationAnimationLocked\}/s);
  assert.match(source, /aria-pressed=\{model === "cgb"\}[\s\S]*disabled=\{presentationAnimationLocked\}/s);
  assert.match(source, /aria-pressed=\{integerScaling\}[\s\S]*disabled=\{scaleAnimationLocked\}/s);
  assert.match(source, /value=\{manualScale\}[\s\S]*disabled=\{scaleAnimationLocked\}/s);
  assert.match(source, /--screen-only-scale/);
  assert.match(source, /availableHeight[\s\S]*- insertedTipHeight[\s\S]*- SCREEN_ONLY_EDGE_GUARD/);
  assert.match(source, /SCREEN_ONLY_CARTRIDGE_OVERHANG = 20/);
  assert.match(css, /\.screen-only \.device-rig\s*\{[^}]*translate 250ms/s);
  assert.match(css, /\.cartridge-hover-rig\s*\{[^}]*translate 250ms/s);
  assert.match(css, /\.cartridge-tooltip-layer\s*\{[^}]*var\(--cartridge-width\) \/ 2 \+ 8px/s);
  assert.match(css, /\.game-cartridge\s*\{[^}]*transform 250ms cubic-bezier\(\.16,\s*\.9,\s*\.24,\s*1\)/s);
  assert.match(source, /function BrandMark\(\)/);
  assert.match(source, /const \[ghostingEnabled, setGhostingEnabled\] = useState\(true\)/);
  assert.match(source, /holdVerb = "LOAD"/);
  assert.match(source, /holdVerb="OVERWRITE"/);
  assert.match(source, /const frame = snapshot\.memory\?\.framebuffer \|\| emulator\.framebuffer/);
  assert.match(source, /previewContext\.putImageData\(imageData, 0, 0\)/);
  assert.match(source, /Frame skipping/);
  assert.match(source, /FRAME_SKIP_PRESETS\[frameSkipRef\.current\]/);
  assert.match(source, /Audio buffering/);
  assert.match(source, /function TechnicalReadout\(/);
  assert.match(source, /Show technical readout/);
  assert.match(source, /SKIPPED\/S/);
  assert.match(source, /MBC3 CLOCK/);
  assert.match(source, /TECHNICAL_READOUT_MEDIA = "\(min-width: 1180px\)"/);
  assert.match(source, /disabled=\{!technicalReadoutSupported\}/);
  assert.match(source, /const showTechnicalReadout = technicalReadoutSupported && technicalReadoutRequested/);
  assert.match(source, /setTechnicalReadoutRequested\(saved\.showTechnicalReadout\)/);
  assert.doesNotMatch(source, /setShowTechnicalReadout/);
  assert.match(source, /<header className="topbar">[\s\S]*<TechnicalReadout[\s\S]*<section className="workspace">/);
  assert.match(css, /\.technical-readout\s*\{[^}]*display:\s*grid[^}]*flex:\s*0 0 auto/s);
  assert.doesNotMatch(css, /\.technical-readout\s*\{[^}]*position:\s*absolute/s);
  assert.match(css, /\.technical-readout\.visible\s*\{[^}]*height:\s*78px/s);
  assert.match(css, /\.technical-readout dd\s*\{[^}]*--metric-value-fit/s);
  assert.match(css, /\.readout-cartridge dl\s*\{[^}]*repeat\(4,/s);
  const technicalCss = css.slice(
    css.indexOf(".technical-readout {"),
    css.indexOf(".key-hint {"),
  );
  assert.doesNotMatch(technicalCss, /text-overflow:\s*ellipsis/);
  assert.match(technicalCss, /white-space:\s*nowrap/);
  assert.doesNotMatch(source, /inert=\{!visible\}/);
  assert.doesNotMatch(css, /\.technical-readout\s*\{[^}]*visibility:/s);
  assert.match(css, /\.technical-open \.topbar\s*\{[^}]*border-bottom-color:\s*transparent/s);
  assert.match(source, /useState\(false\);\s*const \[manualScale, setManualScale\] = useState\(90\)/);
  assert.match(source, /setAudioSampleRate\(context\.sampleRate\)/);
  assert.match(source, /EMBEDDED_LIBRARY_ROMS/);
  assert.match(source, /createBuiltInLibraryRecord/);
  assert.match(source, /createBuiltInLibraryRecords/);
  assert.match(source, /getEmbeddedLibraryRom\(entry\)/);
  assert.match(source, /entry\.builtIn[\s\S]*getEmbeddedLibraryRom\(entry\)/);
  assert.match(source, /builtIn:\s*true/);
  assert.match(source, /LIBRARY_DISCOVERY_KEY/);
  assert.match(source, /rom\.system === "gbc" \? "GBC" : "DMG"/);
  assert.match(source, /className="library-title-row"[\s\S]*<OverflowTitle as="h3"[\s\S]*library-system-tag system-/);
  assert.match(source, /placeholder="SEARCH"/);
  assert.match(source, /className="tabletop-search"[\s\S]*placeholder="SEARCH"/);
  assert.doesNotMatch(source, /TABLETOP · \{String\(visibleRoms\.length\)/);
  assert.doesNotMatch(source, /SEARCH TITLE OR FILE/);
  assert.match(css, /\.library-add-button[\s\S]*transition:/);
  assert.match(css, /\.library-view-toggle[\s\S]*transition:/);
  assert.match(source, /className="tabletop-cartridge-caption"[\s\S]*library-system-tag system-/);
  assert.match(css, /\.library-title-row\s*\{[^}]*display:\s*flex[^}]*align-items:\s*center/s);
  assert.match(css, /\.library-system-tag\s*\{[^}]*font:\s*900 9px\/1/s);
  assert.match(css, /\.library-system-tag\.system-dmg\s*\{[^}]*var\(--magenta\)/s);
  assert.match(css, /\.library-system-tag\.system-gbc\s*\{[^}]*var\(--cyan\)/s);
  assert.match(css, /\.library-results\s*\{[^}]*grid-auto-rows:\s*max-content[^}]*align-content:\s*start/s);
  assert.match(css, /\.library-cartridge-graphic\s*\{[^}]*align-self:\s*start/s);
  assert.match(css, /\.library-tools\s*\{[^}]*position:\s*sticky[^}]*top:\s*65px[^}]*z-index:\s*6[^}]*margin-inline:\s*-28px[^}]*padding:\s*15px 28px[^}]*background:\s*var\(--paper\)[^}]*box-shadow:\s*[\s\S]*?0 -12px 0 12px var\(--paper\),[\s\S]*?0 2px 0 var\(--paper\)/s);
  assert.match(source, /function readLibrarySaveMeta\(/);
  assert.match(source, /<dt>SAVE BATTERY<\/dt>[\s\S]*<FloppyIcon hasData=\{saveMeta\.batteryStored\}/s);
  assert.match(source, /<dt>SAVE STATES<\/dt>[\s\S]*aria-label=\{`\$\{usedStateCount\} of 3 save-state slots used`\}/s);
  assert.match(css, /\.library-state-slots i\.used\s*\{[^}]*background:\s*var\(--cyan\)[^}]*var\(--magenta\)/s);
  assert.match(css, /\.library-deck:not\(\.tabletop-mode\)\s*\{[^}]*isolation:\s*isolate/s);
  assert.match(css, /\.library-deck \.drawer-heading\s*\{[^}]*z-index:\s*7[^}]*box-shadow:\s*0 -12px 0 12px var\(--paper\)/s);
  assert.match(css, /\.segmented::before\s*\{[^}]*transform:\s*translateX\(calc\(var\(--segment-index\) \* 100%\)\)[^}]*transition:\s*transform 210ms/s);
  assert.match(css, /@supports selector\(details::details-content\)[\s\S]*block-size 220ms/s);
  assert.match(source, /new LCDShaderRenderer\(canvas\)/);
  assert.match(source, /ghostStrength: ghostStrength \/ 100/);
  assert.match(source, /DMG_LCD_CONTRAST_BASE = 150/);
  assert.match(source, /DMG_SHARP_CONTRAST_BASE = 112/);
  assert.match(source, /effectiveDmgContrast = dmgContrastBase \+ dmgContrastAdjustment/);
  assert.match(source, /dmgContrast: effectiveDmgContrast \/ 100/);
  assert.match(source, /aria-label="Game Boy contrast adjustment"/);
  assert.doesNotMatch(source, /Relative adjustment · LCD baseline/);
  assert.doesNotMatch(source, /ROMs and artwork stay on this device/);
  assert.match(source, /\+ ADD ROM/);
  assert.doesNotMatch(source, /\+ ADD ROM · \{String\(libraryRoms\.length\)\.padStart\(2, "0"\)\}/);
  assert.doesNotMatch(source, /disabled=\{lcdMode !== "response"\}/);
  assert.doesNotMatch(source, /lcd-pixel-grid|context\.fillRect\(column \* scale/);
  assert.match(source, /className="lcd-output"/);
  assert.match(source, /className="frame-source"/);
  assert.match(shader, /getContext\("webgl2"/);
  assert.match(shader, /averageAbsoluteSine/);
  assert.match(shader, /averagePeriodicBand/);
  assert.match(shader, /periodicBandIntegral/);
  assert.match(shader, /renderDmg/);
  assert.match(shader, /renderCgb/);
  assert.match(shader, /texelFetch/);
  assert.doesNotMatch(shader, /fwidth\(/);
  assert.match(shader, /uSourceSize \/ max\(uOutputSize/);
  assert.match(shader, /displaySyncUntil/);
  assert.match(shader, /window\.requestAnimationFrame\(syncDisplaySize\)/);
  assert.match(shader, /this\.canvas\.getBoundingClientRect\(\)/);
  assert.match(shader, /gl\.framebufferTexture2D/);
  assert.match(shader, /window\.ResizeObserver/);
  assert.match(shader, /getBoundingClientRect\(\)/);
  assert.match(shader, /uDisplayModel == 0/);
  assert.match(shader, /uniform float uDmgContrast/);
  assert.match(shader, /vec3 substrate = vec3\(0\.650, 0\.720, 0\.455\)/);
  assert.doesNotMatch(css, /mix-blend-mode:\s*multiply/);
  assert.doesNotMatch(html, /repeating-linear-gradient\(to right,transparent 0 \.55%/);
  assert.match(source, /const PIXEL_FONT =/);
  assert.doesNotMatch(source, /className="drop-screen"/);
  assert.doesNotMatch(source, /<h2>Embedded BIOS|BUILT-IN BIOS|className="boot-tag"/i);
  assert.doesNotMatch(source, /context\.fillText/);
  assert.match(html, /Audio volume/i);
  assert.match(html, /Choose a Game Boy ROM/i);
  assert.match(html, /DMG compatibility palette/i);
  assert.match(html, /Color theme/i);
  assert.match(html, /System/i);
  assert.match(html, /Presentation mode/i);
  assert.match(html, /Opening a drawer pauses gameplay/i);
  assert.match(html, /Cartridge insertion animation/i);
  assert.match(html, /Integer display scaling/i);
  assert.match(source, /source pixel to a whole block of physical display pixels/i);
  assert.match(source, /DMG LCD shader/i);
  assert.match(source, /GBC shader/i);
  assert.match(html, /GBC LCD color correction/i);
  assert.match(html, /Analog audio coupling/i);
  assert.match(html, /Cartridge save/i);
  assert.match(html, /Emulator snapshots/i);
  assert.match(source, /exportState\(\)/);
  assert.match(source, /importState\(snapshot\)/);
  assert.match(source, /AudioWorkletNode/);
  assert.match(source, /this\.maximum = 3328/);
  assert.match(source, /this\.trimFrames\(this\.buffered - this\.maximum\)/);
  assert.match(source, /data-audio-overruns/);
  assert.match(source, /MINIMUM_BUTTON_PRESS_MS = 50/);
  assert.match(source, /CAN’T CHANGE SCALE — INTEGER SCALING IS ON/);
  assert.match(source, /theme === "system"/);
  assert.match(source, /pauseGame\("menu"\)/);
  assert.match(source, /resumeGame\("menu"\)/);
  assert.match(source, /const anyDrawerOpen = drawerOpen[\s\S]*emulationDrawerOpen[\s\S]*saveDrawerOpen[\s\S]*libraryDrawerOpen/);
  assert.match(source, /if \(anyDrawerOpen && pauseOnMenu\) pauseGame\("menu"\)/);
  assert.match(source, /setCartridgeInserting\(true\)/);
  assert.match(source, /window\.setTimeout\(resolve, 560\)/);
  assert.match(source, /setShowSaveTooltip\(true\)/);
  assert.match(source, /SAVE_TOOLTIP_DURATION = 1500/);
  assert.match(source, /SAVE_TOOLTIP_FADE_DURATION = 300/);
  assert.match(source, /setShowSaveTooltip\(false\)[\s\S]*setSaveTooltipFading\(true\)[\s\S]*SAVE_TOOLTIP_FADE_DURATION/s);
  const replayStart = source.indexOf("const replayCartridgeInsertion");
  const replayEnd = source.indexOf("const flushAudio", replayStart);
  assert.ok(replayStart >= 0 && replayEnd > replayStart);
  const replaySource = source.slice(replayStart, replayEnd);
  assert.doesNotMatch(replaySource, /setShowSaveTooltip\(true\)/);
  assert.match(
    replaySource,
    /setCartridgeInserting\(true\)[\s\S]*window\.setTimeout\([\s\S]*setCartridgeInserting\(false\)[\s\S]*setCartridgePreflight\(false\)/,
  );
  assert.match(source, /setCartridgePreflight\(true\)[\s\S]*afterNextPaint\(\)[\s\S]*waitForVisualStability\(deviceRigRef\.current\)[\s\S]*setCartridgeInserting\(true\)/);
  assert.match(css, /\.screen-only \.console-wrap\s*\{[^}]*--cartridge-width:\s*64%/s);
  assert.match(css, /\.screen-only \.cartridge-visual-rig\s*\{[^}]*clip-path:\s*inset\(-200vh -200vw 0 -200vw\)/s);
  assert.match(css, /\.screen-only \.device-rig\s*\{[^}]*transform:\s*scale\(var\(--screen-only-scale,\s*1\)\)[^}]*transform 180ms cubic-bezier\(\.2,\s*\.8,\s*\.2,\s*1\)/s);
  assert.match(source, /LCD_BEZEL_RATIO = 0\.03/);
  assert.match(source, /LCD_FRAME_RATIO = 1 \+ LCD_BEZEL_RATIO \* 2/);
  assert.doesNotMatch(source, /SCREEN_ONLY_FRAME_BORDER|SCREEN_ONLY_BEZEL_OUTLINE/);
  assert.match(source, /function CartridgeDock\(/);
  assert.match(source, /function CartridgeGraphic\(/);
  assert.match(source, /className="device-rig"/);
  assert.match(source, /function LibraryStackButton\(/);
  assert.match(source, /function RomLibraryDrawer\(/);
  assert.match(source, /libraryView === "tabletop"/);
  assert.match(source, /onClick=\{\(\) => onView\("tabletop"\)\}[\s\S]*TABLE/);
  assert.match(source, /className="tabletop-filter-tabs"/);
  assert.match(source, /sortLibraryRecords\([\s\S]*librarySort,[\s\S]*activeLibraryId/);
  assert.match(source, /option value="alphabetic">ALPHABETIC/);
  assert.match(source, /option value="recent">RECENTLY PLAYED/);
  assert.match(source, /option value="size">GAME SIZE/);
  assert.match(source, /function SaveCenter\(/);
  assert.match(source, /createSaveArchive\(localStorage/);
  assert.match(source, /parseSaveArchive\(await file\.text\(\)\)/);
  assert.match(source, /replaceSaveArchive\(localStorage/);
  assert.match(source, /event\.returnValue = ""/);
  assert.match(source, /title=\{`Switch to \$\{modelLabel\(pendingModel\)\}\?`\}/);
  const modelSwitchStart = source.indexOf("const performModelSwitch");
  const modelSwitchEnd = source.indexOf("const switchModel", modelSwitchStart);
  assert.ok(modelSwitchStart >= 0 && modelSwitchEnd > modelSwitchStart);
  const modelSwitchSource = source.slice(modelSwitchStart, modelSwitchEnd);
  assert.match(modelSwitchSource, /const hasCartridge = Boolean\(romRef\.current\)/);
  assert.match(
    modelSwitchSource,
    /const resumeAfterSwitch = pauseReasonRef\.current === "safety"[\s\S]*if \(resumeAfterSwitch\)[\s\S]*resumeGame\("safety"\)/,
  );
  assert.match(
    modelSwitchSource,
    /if \(hasCartridge\) captureDisplayTransition\(\);\s*else releaseDisplayTransition\(\)/,
  );
  assert.match(modelSwitchSource, /pendingPresentationRef\.current = hasCartridge/);
  assert.match(source, /function ReadoutMetric\(/);
  assert.match(css, /--metric-value-fit/);
  assert.match(source, /listLibraryRoms\(\)/);
  assert.match(source, /putLibraryRom\(libraryRecord\)/);
  assert.match(source, /resolveRomArtwork\(/);
  assert.match(source, /function CataloguingOverlay\(/);
  assert.match(source, /COULDN’T FIND ARTWORK/);
  assert.match(source, /THIS STEP FINISHES AUTOMATICALLY/);
  assert.match(source, /className="catalogue-machine"[\s\S]*catalogue-cartridge-outline[\s\S]*catalogue-cartridge-painted[\s\S]*className="catalogue-scan-line"/);
  assert.match(css, /\.catalogue-machine\s*\{[^}]*position:\s*relative[^}]*aspect-ratio:\s*57\s*\/\s*66/s);
  assert.match(css, /\.catalogue-cartridge\s*\{[^}]*position:\s*absolute[^}]*inset:\s*0[^}]*width:\s*100%[^}]*height:\s*100%/s);
  assert.match(css, /\.catalogue-painting \.catalogue-scan-line\s*\{[^}]*catalogue-paint-wipe/s);
  assert.match(css, /\.catalogue-painting \.catalogue-cartridge-outline \.cart-shell\s*\{[^}]*fill:\s*transparent[^}]*stroke:\s*var\(--ink\)[^}]*animation:\s*none/s);
  assert.match(css, /\.catalogue-painting \.catalogue-cartridge-outline\s*\{[^}]*catalogue-outline-recede\s+1120ms/s);
  assert.match(css, /\.catalogue-painting \.catalogue-cartridge-painted\s*\{[^}]*catalogue-surface-wipe\s+1120ms/s);
  assert.match(css, /@keyframes catalogue-paint-wipe[\s\S]*translateX\(calc\(var\(--catalogue-cart-width\) - 100%\)\)/);
  assert.match(css, /@keyframes catalogue-surface-wipe[\s\S]*clip-path:\s*inset\(0 100% 0 0\)[\s\S]*clip-path:\s*inset\(0\)/);
  assert.match(css, /\.catalogue-shelving \.catalogue-machine\s*\{[^}]*catalogue-shelve/s);
  assert.match(source, /function ConsoleIcon\(/);
  assert.match(source, /console-icon-shell/);
  assert.match(source, /onDrop=\{\(event\) => \{[\s\S]*catalogueFile\(event\.dataTransfer\.files\[0\]\)/);
  assert.match(source, /onChange=\{\(event\) => \{[\s\S]*catalogueFile\(event\.target\.files\?\.\[0\]\)/);
  const catalogueStart = source.indexOf("const catalogueFile");
  const catalogueEnd = source.indexOf("const loadLibraryRom", catalogueStart);
  assert.ok(catalogueStart >= 0 && catalogueEnd > catalogueStart);
  const catalogueSource = source.slice(catalogueStart, catalogueEnd);
  assert.match(catalogueSource, /putLibraryRom\(libraryRecord\)/);
  assert.match(catalogueSource, /ALREADY IN LIBRARY/);
  assert.match(catalogueSource, /EMBEDDED_LIBRARY_ROMS\.find/);
  assert.doesNotMatch(catalogueSource, /loadFile\(|setCartridgePresent\(true\)|romRef\.current\s*=/);
  assert.match(source, /emulator\.setCompatibilityPalette\(id\);\s*if \(romRef\.current\)/);
  assert.match(source, /setCartridgeArtwork\(artworkResult\.artwork\)/);
  assert.match(source, /<image[\s\S]*className="cart-artwork"/);
  assert.doesNotMatch(source, /modelRef\.current\.toUpperCase\(\)/);
  assert.match(source, /const nextCartridgeKind = librarySystem/);
  assert.match(source, /cartridgeKind=\{rom\.system === "gbc" \? "gbc" : "gb"\}/);
  assert.match(source, /BATTERY SAVE READY/);
  assert.match(source, /replayCartridgeInsertion\(/);
  assert.doesNotMatch(source, /INSTANT MACHINE STATE/);
  assert.doesNotMatch(source, /"CGB hardware|>CGB<|CGB LCD color correction|Original CGB startup/);
  assert.match(source, /className=\{`pause-overlay pause-/);
  assert.match(source, /audio\.filterCoefficient \* audio\.previousOutputLeft/);
  assert.match(
    source,
    /audioHighPassCoefficient\([\s\S]*context\.sampleRate,[\s\S]*modelRef\.current/,
  );
  assert.match(source, /'button, input, select, textarea, \[contenteditable="true"\]'/);
  assert.doesNotMatch(source, /load-boot-rom|Choose a .{0,20}boot ROM|accept=["'][^"']*\.bin/i);
  assert.match(css, /html,[\s\S]*body\s*\{[^}]*overflow:\s*hidden[^}]*overscroll-behavior:\s*none/s);
  assert.match(css, /\.app-shell\s*\{[^}]*height:\s*100dvh[^}]*overflow:\s*hidden/s);
  assert.match(css, /\.app-shell:has\(\.control-deck\.open:not\(\.library-deck\)\) \.console-wrap\s*\{[^}]*width:\s*calc\(100% - 564px\)[^}]*margin-right:\s*564px/s);
  assert.match(css, /\.app-shell:has\(\.library-deck\.open\) \.console-wrap\s*\{[^}]*width:\s*calc\(100% - 614px\)[^}]*margin-left:\s*614px/s);
  assert.doesNotMatch(css, /\.drawer-backdrop\s*\{[^}]*backdrop-filter:\s*blur/s);
  assert.match(css, /\.ghost-strength-control\s*\{[^}]*margin-bottom:\s*18px/s);
  assert.match(css, /\.segmented button\.active:not\(:disabled\):hover[\s\S]*background:\s*var\(--acid\)/s);
  assert.match(css, /\.theme-dark #options-drawer \.preference-toggle:not\(:disabled\):hover[\s\S]*background:\s*var\(--options-hover-bg\)/s);
  assert.match(css, /\.theme-dark \.emulation-deck \.preference-toggle:not\(:disabled\):hover[\s\S]*background:\s*var\(--emulation-hover-bg\)/s);
  assert.match(css, /\.theme-dark \.segmented::before,[\s\S]*background:\s*var\(--selected-bg\)/s);
  assert.match(css, /\.library-filters,[\s\S]*\.tabletop-filter-tabs button[\s\S]*box-shadow:\s*none/s);
  assert.match(css, /\.range-control input\.range-hover-latched::-[\s\S]*box-shadow:\s*none/s);
  assert.match(source, /const RANGE_POINTER_BEHAVIOUR = \{[\s\S]*range-hover-latched/s);
  assert.match(source, /type="range"\s*\{\.\.\.RANGE_POINTER_BEHAVIOUR\}/s);
  assert.match(source, /className="tabletop-view-toggle"/);
  assert.match(css, /\.library-add-button:hover,[\s\S]*box-shadow:\s*0 6px 0 var\(--cyan\)/s);
  assert.match(css, /\.library-tools \.library-add-button:hover,[\s\S]*\.tabletop-toolbar \.tabletop-add-button:hover[\s\S]*box-shadow:\s*0 6px 0 var\(--cyan\)/s);
  assert.match(css, /\.library-view-toggle:hover,[\s\S]*box-shadow:\s*-5px 0 0 var\(--magenta\)/s);
  assert.match(css, /\.app-data-summary:hover,\s*\.app-data-summary:focus-within/);
  assert.doesNotMatch(css, /\.app-data-section:hover\s+\.app-data-summary/);
  assert.doesNotMatch(css, /\.pause-overlay\s*\{[^}]*backdrop-filter/s);
  assert.match(css, /\.pause-overlay\s*\{[^}]*inset:\s*-4px[^}]*width:\s*auto[^}]*height:\s*auto[^}]*contain:\s*paint/s);
  assert.match(css, /canvas\.lcd-output\s*\{[^}]*image-rendering:\s*auto/s);
  assert.match(css, /canvas\.frame-source\s*\{[^}]*display:\s*none/s);
  assert.match(css, /\.console-wrap\s*\{[^}]*height:\s*100%[^}]*min-height:\s*0/s);
  assert.match(css, /\.device-rig\s*\{[^}]*left:\s*50%[^}]*top:\s*calc\(50% \+ var\(--console-offset-y,\s*0px\)\)[^}]*transform:\s*translate\(-50%,\s*-50%\) scale\(var\(--console-scale,\s*1\)\)[^}]*transform-origin:\s*center/s);
  assert.match(css, /\.device-rig \.handheld\s*\{[^}]*transform:\s*none/s);
  assert.match(css, /\.screen-only \.dmg-brand\s*\{[^}]*display:\s*none/s);
  assert.match(css, /\.scale-toast\s*\{[^}]*box-shadow:\s*5px 5px 0 var\(--magenta\)/s);
  assert.match(css, /\.state-save-card\s*\{[^}]*var\(--magenta\)/s);
  assert.match(css, /@keyframes cartridge-slide-in/);
  assert.match(css, /@keyframes cartridge-shell-knockback/);
  assert.doesNotMatch(css, /--cartridge-duck/);
  assert.match(css, /@keyframes library-card-in/);
  assert.match(css, /@keyframes library-card-delete/);
  assert.match(css, /\.library-card\.is-deleting \.library-cartridge-graphic\s*\{[^}]*library-cartridge-delete/s);
  assert.match(css, /\.library-stack-trigger\s*\{[^}]*left:\s*0[^}]*translate\(-76px,\s*-50%\)/s);
  assert.match(css, /\.library-deck\s*\{[^}]*inset:\s*0 auto 0 0[^}]*translateX\(-105%\)/s);
  assert.match(css, /\.console-wrap\.cartridge-hovered \.game-cartridge\s*\{/);
  assert.doesNotMatch(css, /\.screen-only \.cartridge-tooltip-layer/);
  assert.match(css, /\.screen-only \.console-wrap\s*\{[^}]*--cartridge-width:\s*64%/s);
  assert.match(css, /\.cartridge-prompt-hint\s*\{[^}]*top:\s*-52px[^}]*opacity:\s*0[^}]*opacity 300ms ease-in-out[^}]*translate 300ms ease-in-out/s);
  assert.match(css, /\.cartridge-prompt-hint\.visible\s*\{[^}]*opacity:\s*1/s);
  assert.match(css, /\.console-wrap\.cartridge-hovered \.cartridge-prompt-hint\s*\{[^}]*transition:\s*none/s);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.cartridge-tooltip-layer\s*\{[^}]*width:\s*148px/s);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.cartridge-info-tooltip::before\s*\{[^}]*display:\s*none/s);
  assert.match(css, /\.library-discovery-hint\.visible\s*\{[^}]*opacity:\s*1/s);
  assert.match(css, /\.save-deck\s*\{[^}]*var\(--cyan\)/s);
  assert.match(css, /\.game-cartridge\s*\{[^}]*aspect-ratio:\s*57 \/ 66/s);
  assert.match(css, /\.gbc-cartridge\s*\{[^}]*--cart-shell:\s*#24252a/s);
  assert.match(source, /function waitForVisualStability\(/);
  assert.match(source, /await waitForVisualStability\(deviceRigRef\.current\)/);
  assert.match(css, /\.cartridge-preflight \.game-cartridge\s*\{[^}]*translate\(-50%,\s*var\(--cart-insert-start\)\)/s);
  assert.match(css, /\.console-wrap\.model-cgb \.game-cartridge\s*\{[^}]*--cart-insert-start:\s*-55\.8%[^}]*--cart-insert-overshoot:\s*2\.6%/s);
  assert.match(css, /@keyframes cartridge-slide-in\s*\{[\s\S]*var\(--cart-insert-start\)[\s\S]*var\(--cart-insert-impact\)[\s\S]*var\(--cart-insert-overshoot\)[\s\S]*var\(--cart-insert-rebound\)/s);
  assert.match(source, /className="dpad-glyphs"/);
  assert.match(css, /\.dpad-glyphs\s*\{[^}]*translate\(var\(--dpad-press-x,[^}]*rotateX\(var\(--dpad-tilt-x/s);
  assert.match(css, /\.cgb \.dpad-glyph-up\s*\{[^}]*clip-path:\s*polygon/s);
  assert.match(css, /\.library-tabletop\s*\{[^}]*overflow:\s*auto/s);
  assert.match(css, /\.library-tools\s*\{[^}]*position:\s*sticky[^}]*top:\s*65px[^}]*background:\s*var\(--paper\)/s);
  assert.match(css, /\.screen-frame\s*\{[^}]*container-type:\s*inline-size[^}]*isolation:\s*isolate[^}]*overflow:\s*clip[^}]*border:\s*calc\(var\(--lcd-bezel-width,\s*8px\) \* 2 \/ 3\) solid #292c32/s);
  assert.match(css, /\.screen-frame canvas\.lcd-output,[\s\S]*\.screen-frame \.pause-overlay\s*\{[^}]*clip-path:\s*inset\(0\)/s);
  assert.match(css, /\.screen-only \.screen-frame\s*\{[^}]*width:\s*var\(--screen-frame-width\)[^}]*box-shadow:\s*none/s);
  assert.doesNotMatch(css, /\.screen-only \.screen-frame\s*\{[^}]*border-width:/s);
  assert.match(source, /dimmed:\s*paused && running/);
  assert.match(shader, /uniform float uDimFactor/);
  assert.match(shader, /averageAbsoluteSine\(nativePosition\.x, footprint\.x\)/);
  assert.match(shader, /sharpColor \* uDimFactor/);
  assert.match(shader, /clamp\(color, 0\.0, 1\.0\) \* uDimFactor/);
  assert.match(shader, /animateDimFactor\(target\)[\s\S]*duration = 260[\s\S]*this\.dimFactor = start \+ \(target - start\) \* eased/s);
  assert.doesNotMatch(css, /is-dimmed|brightness\(\.34\)/);
  assert.match(css, /\.pause-overlay\s*\{[^}]*background:\s*transparent/s);
  assert.match(css, /\.pause-overlay\s*\{[^}]*inset:\s*-4px[^}]*contain:\s*paint/s);
  assert.match(css, /\.console-wrap\s*\{[^}]*overflow:\s*clip/s);
  assert.match(source, /viewBox="0 0 570 660"/);
  assert.match(source, /className="cart-label-paper" x="90" y="120" width="380" height="380"/);
  assert.match(source, /className="cart-label-outline" x="90" y="120" width="380" height="380"/);
  assert.match(source, /className="cart-shell-outline"/);
  assert.match(source, /className="cart-grip-lines"/);
  assert.doesNotMatch(source, /cart-save-panel|cart-save-text/);
  assert.doesNotMatch(css, /\.inserted-cart-mini/);
});

test("renders reference-matched DMG and supplied-purple GBC shells", async () => {
  const source = await readFile(new URL("../app/Emulator.jsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(source, /dmg-bezel-label/);
  assert.match(source, /DOT MATRIX WITH STEREO SOUND/);
  assert.match(source, /className="dmg-brand"/);
  assert.match(source, /model === "cgb" \? 56 : 6/);
  assert.match(css, /\.handheld\.dmg\s*\{[^}]*background:\s*#d8d7d0/s);
  assert.match(css, /\.handheld\.cgb\s*\{[^}]*background:\s*#5543bd/s);
  assert.match(css, /\.dmg \.display-bezel\s*\{[^}]*padding:\s*28px 42px/s);
  assert.match(css, /\.dmg \.power-label\s*\{[^}]*left:\s*0[^}]*width:\s*36px[^}]*font-size:\s*6px/s);
  assert.match(css, /\.action-label\s*\{[^}]*top:\s*70px/s);
  assert.match(css, /\.dmg \.meta-buttons\s*\{[^}]*left:\s*91px[^}]*top:\s*183px[^}]*transform:\s*none/s);
  assert.match(css, /\.dmg \.meta-buttons \.control-button\s*\{[^}]*transform:\s*rotate\(-22deg\)/s);
  assert.match(css, /\.handheld\.cgb\s*\{[^}]*border-radius:\s*14px 14px 50% 50%\s*\/\s*14px 14px 46px 46px/s);
  assert.match(css, /\.cgb \.screen-caption\s*\{[^}]*--cgb-caption-gap:\s*16px[^}]*--cgb-caption-height:\s*16px[^}]*left:\s*50%[^}]*bottom:\s*var\(--cgb-caption-gap\)[^}]*height:\s*var\(--cgb-caption-height\)[^}]*transform:\s*translateX\(-50%\)/s);
  assert.match(css, /\.cgb \.screen-caption strong\s*\{[^}]*font-size:\s*16px/s);
  assert.match(css, /\.cgb \.screen-frame\s*\{[^}]*position:\s*absolute[^}]*left:\s*50%[^}]*bottom:\s*48px[^}]*border-color:\s*#0d0f13[^}]*box-shadow:\s*none[^}]*translate:\s*-50% 0/s);
  assert.match(css, /\.screen-only \.cgb \.screen-frame\s*\{[^}]*border-radius:\s*calc\(var\(--lcd-bezel-width,\s*8px\) \* 1\.1\)/s);
  assert.match(css, /\.cgb \.screen-inner\s*\{[^}]*border-radius:\s*calc\(var\(--lcd-bezel-width,\s*8px\) \* \.1\)[^}]*background:\s*#0d0f13/s);
  assert.match(css, /\.screen-only \.screen-frame\s*\{[^}]*position:\s*relative[^}]*bottom:\s*auto[^}]*translate:\s*0 0/s);
  assert.match(css, /\.cgb \.meta-buttons\s*\{[^}]*left:\s*51\.5%[^}]*transform:\s*translateX\(-50%\)/s);
  assert.match(css, /\.cgb-nintendo\s*\{[^}]*font:\s*800 15px\/1/s);
  assert.match(css, /\.cgb \.dpad\s*\{[^}]*background:\s*transparent/s);
  assert.match(css, /\.cgb \.dpad-outline\s*\{[^}]*stroke:\s*#202127/s);
  assert.match(css, /\.cgb \.dpad-cross\s*\{[^}]*--dpad-surface:\s*#3b3b43/s);
  assert.match(css, /\.dpad-outline\s*\{[^}]*stroke-width:\s*2[^}]*stroke-linejoin:\s*miter/s);
  assert.match(css, /\.cgb \.action-buttons \.control-button\s*\{[^}]*background:\s*#3b3b43/s);
  assert.match(css, /\.dmg \.power-label i,[^}]*\.cgb \.power-label i\s*\{[^}]*background:\s*#391a26/s);
  assert.match(css, /\.action-buttons \.control-button:active,[^}]*\.action-buttons \.control-button\.is-pressed\s*\{[^}]*inset 0 3px 5px/s);
  assert.match(css, /\.cgb \.speaker\s*\{[^}]*grid-template-columns:\s*repeat\(7,\s*5px\)[^}]*grid-template-rows:\s*repeat\(8,\s*5px\)/s);
});

test("protects cartridge changes and keeps hardware and library labels readable", async () => {
  const source = await readFile(new URL("../app/Emulator.jsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(source, /const LOAD_HOLD_DURATION = 1000/);
  assert.match(source, /function HoldToLoadButton\(/);
  assert.match(source, /data-requires-hold=\{requiresHold \? "true" : "false"\}/);
  assert.match(source, /ARE YOU SURE\? UNSAVED PROGRESS WILL BE LOST/);
  assert.match(source, /holdShakeRef\.current = buttonRef\.current\?\.animate\?\./);
  assert.match(source, /requiresHold=\{cartridgePresent\}/);
  assert.match(source, /model: snapshot\.model[\s\S]*preview/);
  assert.match(source, /snapshot\.memory\?\.framebuffer \|\| emulator\.framebuffer/);
  assert.match(source, /snapshot\.model !== modelRef\.current/);
  assert.match(source, /save-state-preview-console\$\{slot \? ` model-\$\{slot\.model/);
  assert.match(source, /data-model=\{slot\?\.model \|\| "empty"\}/);
  assert.match(css, /\.hold-to-load\[data-holding="true"\] \.hold-load-safety::before\s*\{[^}]*hold-load-fill 1s linear forwards/s);
  assert.match(css, /\.hold-to-load\[data-requires-hold="true"\]:not\(\.tabletop-cartridge\):hover \.hold-load-safety/);
  assert.match(css, /\.action-label-b\s*\{[^}]*left:\s*22px/s);
  assert.match(css, /\.action-label-a\s*\{[^}]*right:\s*22px/s);
  assert.match(css, /\.cgb \.action-buttons \.control-button > span\s*\{[^}]*rotate\(22deg\)/s);
  assert.match(css, /\.dpad-cross::after\s*\{[^}]*linear-gradient\([^}]*135deg[^}]*22%[^}]*78%/s);
  assert.match(source, /function OverflowTitle\(/);
  assert.match(source, /const contentWidth = title\.clientWidth[\s\S]*style\.paddingLeft[\s\S]*style\.paddingRight/);
  assert.match(source, /text\.scrollWidth \+ 24/);
  assert.match(source, /\{travel > 0 && <span aria-hidden="true">\{children\}<\/span>\}/);
  assert.match(css, /\.overflow-title-track > span\s*\{[^}]*flex:\s*0 0 auto/s);
  assert.match(css, /\.overflow-title\.is-overflowing \.overflow-title-track\s*\{[^}]*overflow-title-scroll[^}]*linear infinite/s);
  assert.match(css, /\.tabletop-cartridge \.overflow-title\.is-overflowing \.overflow-title-track\s*\{[^}]*animation:\s*none[^}]*translateX\(0\)/s);
  assert.match(css, /\.tabletop-cartridge:hover \.overflow-title\.is-overflowing \.overflow-title-track[\s\S]*overflow-title-scroll var\(--title-scroll-duration\)/s);
  assert.match(css, /\.library-card\.is-active \.library-title-row\s*\{[^}]*padding-right:\s*92px/s);
  assert.match(source, /className="key-hint controls-key-hint"/);
  assert.match(css, /\.controls-key-hint\s*\{[^}]*display:\s*flex[^}]*white-space:\s*nowrap/s);
  assert.match(css, /\.model-switch button\.active \.console-option-icon\s*\{[^}]*drop-shadow\(3px 3px 0 var\(--cyan\)\)/s);
  assert.doesNotMatch(css, /\.model-switch button\.active \.console-option-icon\s*\{[^}]*0 0 2px/s);
});
